import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./AuthProvider/page";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <NextAuthProvider>
          <Header/>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
